import type { CentoUIConfig } from 'centoui-cli'

export default {
  icons: {
    check: 'lucide:check',
    chevronDoubleLeft: 'lucide:chevrons-left',
    chevronDoubleRight: 'lucide:chevrons-right',
    chevronDown: 'lucide:chevron-down',
    chevronLeft: 'lucide:chevron-left',
    chevronRight: 'lucide:chevron-right',
    chevronUp: 'lucide:chevron-up',
    close: 'lucide:x',
    ellipsis: 'lucide:ellipsis',
  },
} satisfies Pick<CentoUIConfig, 'icons'>

// NB: Not yet in use by any component. These are just examples

// arrowDown: 'lucide:arrow-down',
// arrowLeft: 'lucide:arrow-left',
// arrowRight: 'lucide:arrow-right',
// arrowUp: 'lucide:arrow-up',
// caution: 'lucide:triangle-alert',
// copy: 'lucide:copy',
// copyCheck: 'lucide:badge-check',
// dark: 'lucide:moon',
// drag: 'lucide:grip-vertical',
// error: 'lucide:circle-x',
// external: 'lucide:arrow-up-right',
// eye: 'lucide:eye',
// eyeOff: 'lucide:eye-off',
// file: 'lucide:file',
// folder: 'lucide:folder',
// folderOpen: 'lucide:folder-open',
// hash: 'lucide:hash',
// info: 'lucide:info',
// light: 'lucide:sun',
// loading: 'lucide:loader-circle',
// menu: 'lucide:menu',
// minus: 'lucide:minus',
// panelClose: 'lucide:panel-left-close',
// panelOpen: 'lucide:panel-left-open',
// plus: 'lucide:plus',
// reload: 'lucide:refresh-cw',
// search: 'lucide:search',
// stop: 'lucide:square',
// success: 'lucide:circle-check',
// system: 'lucide:monitor',
// tip: 'lucide:lightbulb',
// upload: 'lucide:upload',
// warning: 'lucide:triangle-alert',
