/**
 * Mirrors the `globals.json` registry schema.
 * Defines properties that every CentoUI project must have.
 */
export type GlobalsRegistry = {
  /**
   * NPM packages that are required in every CentoUI project.
   * Keys are package names; values are semver version ranges (e.g. `"^4.2.2"`).
   */
  packageDeps: Record<string, string>
}

/**
 * Mirrors the `component.json` registry schema.
 * Describes a single installable CentoUI component.
 */
export type ComponentRegistry = {
  /** Unique identifier for the component. Matches its registry filename (e.g. `"button"`). */
  name: string

  /** Short human-readable description shown in CLI output. */
  description?: string

  /**
   * Source file paths relative to `packages/core/src/`.
   * All paths start with `components/` by convention (e.g. `"components/button/button.vue"`).
   * The CLI fetches each file from GitHub and writes it into the user's components directory.
   */
  files: string[]

  /**
   * Names of other CentoUI components that must be installed alongside this one.
   * The CLI resolves the full dependency tree automatically.
   */
  componentDeps: string[]

  /**
   * NPM packages required specifically by this component,
   * in addition to the global dependencies defined in `GlobalsRegistry`.
   * Keys are package names; values are semver version ranges.
   */
  packageDeps: Record<string, string>
}

/**
 * The complete CentoUI registry — the `index.json` file fetched from GitHub.
 * Contains global project dependencies and the full list of installable components.
 */
export type Registry = {
  /** Global properties that every CentoUI project must have. */
  globals: GlobalsRegistry

  /** All components that can be installed with `centoui add`. */
  components: ComponentRegistry[]
}

/**
 * The user-side CentoUI configuration, stored in `centoui.config.ts`.
 * Generated by `centoui init` and consumed by every subsequent CLI command.
 */
export type CentoUIConfig = {
  /** The CentoUI version this project was initialised with. */
  version: string

  /** Relative path (from project root) to the directory where components are installed. */
  componentsDir: string

  /** Relative path (from project root) to the CSS file that receives theme and component styles. */
  themeFilePath: string

  /**
   * Maps internal CentoUI icon slot names to Iconify icon IDs.
   * Components reference icon slots by their internal name so you can swap icon libraries freely.
   *
   * @example { menu: 'lucide:menu', close: 'lucide:x' }
   */
  icons: Record<string, string>
}
